/**
 * One `GET /admin/ops` document exactly as `PlatformStatusOut` serialises it
 * (camelCase), shared by the binding, helper and page tests. A fixture module rather
 * than an export from a test file, so importing it does not re-run that file's suite.
 */

/** The document exactly as `PlatformStatusOut` serialises it (camelCase). */
export const WIRE_STATUS = {
  generatedAt: '2026-09-10T09:30:00+00:00',
  env: 'dev',
  version: '0.1.0',
  release: null,
  providers: { llm: 'mock', render: 'mock', billing: 'mock', mail: 'dev-echo' },
  sentry: 'off',
  migrations: {
    current: [],
    heads: ['0016_compliance_summary'],
    upToDate: false,
    reason: 'alembic_version is absent: migrations have never run on this database.',
  },
  queues: [
    {
      name: 'garh:queue:solver',
      worker: 'solver',
      pending: 2,
      delayed: 1,
      processing: 0,
      dead: 0,
    },
    { name: 'garh:queue:render', worker: 'render', pending: 0, delayed: 0, processing: 1, dead: 3 },
    {
      name: 'garh:queue:drawings',
      worker: 'drawings',
      pending: 0,
      delayed: 0,
      processing: 0,
      dead: 0,
    },
  ],
  workers: [
    {
      worker: 'solver',
      instance: 'host-solver-1',
      hostname: 'host-solver',
      sentAt: '2026-09-10T09:29:50+00:00',
      ageSeconds: 10,
      intervalSeconds: 10,
      stale: false,
      draining: false,
      uptimeSeconds: 7_400,
      inFlight: 1,
      concurrency: 2,
      jobsReceived: 5,
      jobsSucceeded: 4,
      jobsFailed: 1,
      jobsRetried: 0,
      jobsDeadLettered: 0,
      p50DurationMs: 800,
      p95DurationMs: 2_400,
      providerLlm: 'mock',
      providerRender: 'mock',
      sentry: 'off',
      release: null,
      env: 'dev',
    },
    {
      worker: 'render',
      instance: 'host-render-1',
      hostname: 'host-render',
      sentAt: '2026-09-10T09:29:15+00:00',
      ageSeconds: 45,
      intervalSeconds: 10,
      stale: true,
      draining: false,
      uptimeSeconds: 40,
      inFlight: 0,
      concurrency: 1,
      jobsReceived: 0,
      jobsSucceeded: 0,
      jobsFailed: 0,
      jobsRetried: 0,
      jobsDeadLettered: 0,
      p50DurationMs: 0,
      p95DurationMs: 0,
      providerLlm: 'mock',
      providerRender: 'stability',
      sentry: 'on',
      release: 'abc123',
      env: 'dev',
    },
  ],
  jobs: [
    {
      kind: 'render',
      counts: { queued: 0, running: 0, succeeded: 0, failed: 0, cancelled: 0 },
      terminalCount: 0,
      p50Ms: 0,
      p95Ms: 0,
      maxMs: 0,
    },
    {
      kind: 'solver',
      counts: { queued: 1, running: 0, succeeded: 2, failed: 1, cancelled: 0 },
      terminalCount: 3,
      p50Ms: 30_000,
      p95Ms: 84_000,
      maxMs: 90_000,
    },
  ],
  exportJobsLive: 2,
  jobWindowHours: 24,
  observability: {
    sentry: 'off',
    logFormat: 'json',
    workersReporting: 2,
    workersMissing: ['drawings'],
    workersStale: ['host-render-1'],
    redis: 'ok',
    database: 'ok',
  },
};
