/**
 * Spec for the NOAA solar position port.
 *
 * TWO LAYERS OF DEFENCE, because "matches a table I generated" alone proves
 * nothing about the table:
 *
 *  1. A PINNED REFERENCE TABLE (36 rows: 3 city latitudes × solstices +
 *     equinoxes × 3 times of day). Generated by an independent Python port of
 *     the same published NOAA equations, itself sanity-checked against the
 *     textbook identities in layer 2 before pinning. Tolerance 0.01° — the
 *     two ports share equations, so anything past float noise is a port bug.
 *
 *  2. PUBLISHED PHYSICS the table cannot fake:
 *      - solar declination at the solstices = ±23.44° (the published axial
 *        tilt; NOAA's calculator shows 23.43x for 2026) — tolerance 0.05°;
 *      - |declination| < 0.5° on the equinoxes;
 *      - noon altitude = 90° − |lat − declination| — tolerance 0.05°;
 *      - noon sun is NORTH of Bengaluru and Hyderabad on the June solstice
 *        (both sit south of the Tropic of Cancer) and south of Delhi;
 *      - equinox sunrise bears due east: azimuth 90° ± 1.5° where the
 *        elevation crosses zero;
 *      - NOAA refraction: ≈ +0.56° at the horizon, ≈ +0.016° at 45°, 0 at 89°.
 *
 * All elevations here are GEOMETRIC (`elevationDeg`); refraction is asserted
 * separately so neither test can hide an error in the other.
 */

import { describe, expect, it } from 'vitest';

import { CITY_CENTROIDS, cityForPack } from './cities';
import { istToUtcMs, refractionDeg, solarPosition, utcMsToIst } from './solar';

interface RefRow {
  readonly city: string;
  /** DD-MM-YYYY, IST. */
  readonly date: string;
  readonly time: string;
  readonly azimuthDeg: number;
  readonly elevationDeg: number;
}

/** Pinned by scripts noted in the header. Solstices + equinoxes, 2026, IST. */
const REFERENCE: readonly RefRow[] = [
  { city: 'blr', date: '20-03-2026', time: '09:00', azimuthDeg: 100.2412, elevationDeg: 37.0163 },
  { city: 'blr', date: '20-03-2026', time: '12:30', azimuthDeg: 183.1784, elevationDeg: 76.8833 },
  { city: 'blr', date: '20-03-2026', time: '16:00', azimuthDeg: 260.398, elevationDeg: 35.6645 },
  { city: 'blr', date: '21-06-2026', time: '09:00', azimuthDeg: 70.0659, elevationDeg: 41.2911 },
  { city: 'blr', date: '21-06-2026', time: '12:30', azimuthDeg: 349.2801, elevationDeg: 79.3368 },
  { city: 'blr', date: '21-06-2026', time: '16:00', azimuthDeg: 289.7348, elevationDeg: 37.3493 },
  { city: 'blr', date: '23-09-2026', time: '09:00', azimuthDeg: 101.4814, elevationDeg: 40.6489 },
  { city: 'blr', date: '23-09-2026', time: '12:30', azimuthDeg: 199.0905, elevationDeg: 76.1842 },
  { city: 'blr', date: '23-09-2026', time: '16:00', azimuthDeg: 261.5133, elevationDeg: 32.0183 },
  { city: 'blr', date: '21-12-2026', time: '09:00', azimuthDeg: 126.8343, elevationDeg: 29.5251 },
  { city: 'blr', date: '21-12-2026', time: '12:30', azimuthDeg: 184.7828, elevationDeg: 53.4657 },
  { city: 'blr', date: '21-12-2026', time: '16:00', azimuthDeg: 236.3411, elevationDeg: 24.5864 },
  { city: 'ncr', date: '20-03-2026', time: '09:00', azimuthDeg: 110.5742, elevationDeg: 32.467 },
  { city: 'ncr', date: '20-03-2026', time: '12:30', azimuthDeg: 180.6974, elevationDeg: 61.2587 },
  { city: 'ncr', date: '20-03-2026', time: '16:00', azimuthDeg: 249.9879, elevationDeg: 31.9802 },
  { city: 'ncr', date: '21-06-2026', time: '09:00', azimuthDeg: 84.2884, elevationDeg: 44.4536 },
  { city: 'ncr', date: '21-06-2026', time: '12:30', azimuthDeg: 197.4242, elevationDeg: 84.5871 },
  { city: 'ncr', date: '21-06-2026', time: '16:00', azimuthDeg: 277.0811, elevationDeg: 41.3755 },
  { city: 'ncr', date: '23-09-2026', time: '09:00', azimuthDeg: 113.0749, elevationDeg: 35.6033 },
  { city: 'ncr', date: '23-09-2026', time: '12:30', azimuthDeg: 188.4705, elevationDeg: 61.0093 },
  { city: 'ncr', date: '23-09-2026', time: '16:00', azimuthDeg: 252.319, elevationDeg: 28.8004 },
  { city: 'ncr', date: '21-12-2026', time: '09:00', azimuthDeg: 132.1027, elevationDeg: 19.255 },
  { city: 'ncr', date: '21-12-2026', time: '12:30', azimuthDeg: 183.1572, elevationDeg: 37.8839 },
  { city: 'ncr', date: '21-12-2026', time: '16:00', azimuthDeg: 231.4682, elevationDeg: 15.6181 },
  { city: 'hyd', date: '20-03-2026', time: '09:00', azimuthDeg: 103.8622, elevationDeg: 36.937 },
  { city: 'hyd', date: '20-03-2026', time: '12:30', azimuthDeg: 185.3468, elevationDeg: 72.4175 },
  { city: 'hyd', date: '20-03-2026', time: '16:00', azimuthDeg: 257.7294, elevationDeg: 33.9804 },
  { city: 'hyd', date: '21-06-2026', time: '09:00', azimuthDeg: 73.889, elevationDeg: 43.4774 },
  { city: 'hyd', date: '21-06-2026', time: '12:30', azimuthDeg: 335.2959, elevationDeg: 83.3099 },
  { city: 'hyd', date: '21-06-2026', time: '16:00', azimuthDeg: 286.5266, elevationDeg: 37.9048 },
  { city: 'hyd', date: '23-09-2026', time: '09:00', azimuthDeg: 105.5617, elevationDeg: 40.4541 },
  { city: 'hyd', date: '23-09-2026', time: '12:30', azimuthDeg: 197.3673, elevationDeg: 71.7223 },
  { city: 'hyd', date: '23-09-2026', time: '16:00', azimuthDeg: 259.1955, elevationDeg: 30.4288 },
  { city: 'hyd', date: '21-12-2026', time: '09:00', azimuthDeg: 129.245, elevationDeg: 27.4826 },
  { city: 'hyd', date: '21-12-2026', time: '12:30', azimuthDeg: 185.5881, elevationDeg: 48.9925 },
  { city: 'hyd', date: '21-12-2026', time: '16:00', azimuthDeg: 235.2312, elevationDeg: 21.3917 },
];

function utcMsFor(ddmmyyyy: string, hhmm: string): number {
  const [dd, mm, yyyy] = ddmmyyyy.split('-').map(Number) as [number, number, number];
  const [h, m] = hhmm.split(':').map(Number) as [number, number];
  return istToUtcMs({ year: yyyy, month: mm, day: dd }, h * 60 + m);
}

function city(packId: string): { latDeg: number; lonDeg: number } {
  const c = cityForPack(packId);
  if (c === null) throw new Error(`no centroid for ${packId}`);
  return c;
}

const SOLSTICE_TILT_DEG = 23.44; // published obliquity of the ecliptic (2026: 23.436)

describe('solarPosition — pinned NOAA reference table', () => {
  it.each(REFERENCE)('$city $date $time IST', (row) => {
    const { latDeg, lonDeg } = city(row.city);
    const pos = solarPosition(utcMsFor(row.date, row.time), latDeg, lonDeg);
    expect(pos.azimuthDeg).toBeCloseTo(row.azimuthDeg, 2); // ±0.01°
    expect(pos.elevationDeg).toBeCloseTo(row.elevationDeg, 2);
  });
});

describe('solarPosition — published physics, not the table', () => {
  it('declination hits ±23.44° at the solstices and ~0° at the equinoxes', () => {
    const { latDeg, lonDeg } = city('blr');
    const jun = solarPosition(utcMsFor('21-06-2026', '12:30'), latDeg, lonDeg);
    const dec = solarPosition(utcMsFor('21-12-2026', '12:30'), latDeg, lonDeg);
    expect(Math.abs(jun.declinationDeg - SOLSTICE_TILT_DEG)).toBeLessThan(0.05);
    expect(Math.abs(dec.declinationDeg + SOLSTICE_TILT_DEG)).toBeLessThan(0.05);
    for (const date of ['20-03-2026', '23-09-2026']) {
      const eq = solarPosition(utcMsFor(date, '12:30'), latDeg, lonDeg);
      expect(Math.abs(eq.declinationDeg)).toBeLessThan(0.5);
    }
  });

  it('noon altitude = 90° − |lat − declination| at every city, every key date', () => {
    for (const c of CITY_CENTROIDS) {
      for (const date of ['20-03-2026', '21-06-2026', '23-09-2026', '21-12-2026']) {
        // Scan for solar noon at 1-minute resolution — IST noon is not solar noon.
        let best = { elevationDeg: -Infinity, declinationDeg: 0, azimuthDeg: 0 };
        for (let minutes = 10 * 60; minutes < 15 * 60; minutes++) {
          const [dd, mm, yyyy] = date.split('-').map(Number) as [number, number, number];
          const pos = solarPosition(
            istToUtcMs({ year: yyyy, month: mm, day: dd }, minutes),
            c.latDeg,
            c.lonDeg,
          );
          if (pos.elevationDeg > best.elevationDeg) best = pos;
        }
        const ideal = 90 - Math.abs(c.latDeg - best.declinationDeg);
        expect(Math.abs(best.elevationDeg - ideal)).toBeLessThan(0.05);
        // South of the Tropic of Cancer the June-solstice noon sun is NORTH.
        const sunNorth = best.azimuthDeg < 90 || best.azimuthDeg > 270;
        expect(sunNorth).toBe(c.latDeg < best.declinationDeg);
      }
    }
  });

  it('equinox sunrise bears due east (azimuth 90° ± 1.5° at the zero crossing)', () => {
    for (const c of CITY_CENTROIDS) {
      let crossed = false;
      for (let minutes = 5 * 60; minutes < 8 * 60; minutes++) {
        const pos = solarPosition(
          istToUtcMs({ year: 2026, month: 3, day: 20 }, minutes),
          c.latDeg,
          c.lonDeg,
        );
        if (pos.elevationDeg >= 0) {
          expect(Math.abs(pos.azimuthDeg - 90)).toBeLessThan(1.5);
          crossed = true;
          break;
        }
      }
      expect(crossed).toBe(true);
    }
  });

  it('morning elevation rises monotonically toward noon', () => {
    const { latDeg, lonDeg } = city('hyd');
    let prev = -Infinity;
    for (let minutes = 7 * 60; minutes <= 12 * 60; minutes += 30) {
      const pos = solarPosition(
        istToUtcMs({ year: 2026, month: 6, day: 21 }, minutes),
        latDeg,
        lonDeg,
      );
      expect(pos.elevationDeg).toBeGreaterThan(prev);
      prev = pos.elevationDeg;
    }
  });
});

describe('refractionDeg — NOAA piecewise correction', () => {
  it('≈ +0.56° at the horizon, ≈ +0.016° at 45°, 0 high overhead', () => {
    expect(refractionDeg(0.5)).toBeCloseTo(0.4167, 3);
    expect(refractionDeg(-0.5)).toBeCloseTo(0.5616, 3);
    expect(refractionDeg(45)).toBeCloseTo(0.0161, 3);
    expect(refractionDeg(89)).toBe(0);
  });

  it('apparentElevationDeg = geometric + refraction', () => {
    const { latDeg, lonDeg } = city('blr');
    const pos = solarPosition(utcMsFor('20-03-2026', '06:45'), latDeg, lonDeg);
    expect(pos.apparentElevationDeg).toBeCloseTo(
      pos.elevationDeg + refractionDeg(pos.elevationDeg),
      9,
    );
  });
});

describe('IST clock helpers', () => {
  it('istToUtcMs/utcMsToIst round-trip and honour the +5:30 offset', () => {
    const ms = istToUtcMs({ year: 2026, month: 6, day: 21 }, 12 * 60 + 30);
    // 12:30 IST = 07:00 UTC.
    expect(new Date(ms).toISOString()).toBe('2026-06-21T07:00:00.000Z');
    const back = utcMsToIst(ms);
    expect(back.date).toEqual({ year: 2026, month: 6, day: 21 });
    expect(back.minutesOfDay).toBe(750);
  });

  it('crosses midnight correctly (00:10 IST is the previous UTC day)', () => {
    const ms = istToUtcMs({ year: 2026, month: 1, day: 1 }, 10);
    expect(new Date(ms).toISOString()).toBe('2025-12-31T18:40:00.000Z');
    expect(utcMsToIst(ms).date).toEqual({ year: 2026, month: 1, day: 1 });
  });
});
