/**
 * HatchSwatch.tsx — one pattern, drawn.
 *
 * The swatch draws the pattern's REAL line families, generated by the port of
 * the renderer's own generator (`geometry.ts`) from the definitions the drift
 * test pins to `hatch_patterns.py`. Not a PNG, not a CSS gradient: a picker
 * whose tiles are approximations teaches an architect something false about
 * what the sheet will print, and this repo has already shipped a version of
 * that bug (earth drawn as cross).
 *
 * Three details that matter for it to look right at 40 pixels:
 *
 *  * The SVG viewport clips. Hatch lines are generated across the box's
 *    bounding square and run past its corners, exactly as they do on a sheet
 *    before the renderer clips them to the wall outline; `overflow: hidden` on
 *    an `<svg>` with a `viewBox` is that clip, for free.
 *  * Stroke width is computed back from the requested pixel size, so the line
 *    is ~1 px whether the swatch is 24 px in a list or 96 px in a preview. A
 *    fixed user-unit width would be invisible at one size and a blob at the
 *    other.
 *  * `stroke-linecap: round` where the pattern's cycle is dots (AR-SAND,
 *    AR-CONC): a dot is drawn as a very short dash, and a butt cap makes those
 *    disappear.
 */

import { useMemo, type CSSProperties } from 'react';

import { cn } from '@garh/ui';

import { hatchPattern, type HatchPatternKey } from './patterns';
import { familyPath, swatchGeometry } from './swatch';

/** Target stroke weight on screen, in CSS pixels. */
const STROKE_PX = 1.15;

export interface HatchSwatchProps {
  readonly pattern: HatchPatternKey;
  /** Edge length in CSS pixels. */
  readonly size?: number;
  readonly className?: string | undefined;
  readonly style?: CSSProperties | undefined;
  /**
   * Accessible name. Defaults to the pattern's own label; pass `null` to mark
   * the swatch decorative when a visible label already names it.
   */
  readonly label?: string | null | undefined;
}

export function HatchSwatch({
  pattern,
  size = 40,
  className,
  style,
  label,
}: HatchSwatchProps): JSX.Element {
  const geometry = useMemo(() => swatchGeometry(pattern), [pattern]);
  const strokeWidth = (geometry.units * STROKE_PX) / Math.max(size, 1);
  const name = label === undefined ? hatchPattern(pattern).label : label;

  return (
    <svg
      width={size}
      height={size}
      viewBox={`0 0 ${String(geometry.units)} ${String(geometry.units)}`}
      className={cn('shrink-0 text-ink', className)}
      style={style}
      data-pattern={pattern}
      {...(name === null ? { 'aria-hidden': true } : { role: 'img', 'aria-label': name })}
    >
      {/* The paper the pattern sits on — without it a dark theme shows hatch
          lines floating on the panel background rather than on a drawing. */}
      <rect
        x={0}
        y={0}
        width={geometry.units}
        height={geometry.units}
        className="fill-surface"
        stroke="none"
      />
      {geometry.solid ? (
        <rect
          x={0}
          y={0}
          width={geometry.units}
          height={geometry.units}
          fill="currentColor"
          stroke="none"
        />
      ) : (
        geometry.families.map((family, index) => (
          <path
            // Families are positional: the same pattern always generates the
            // same list in the same order, so the index IS the identity here.
            key={`${pattern}-${String(index)}`}
            d={familyPath(family)}
            fill="none"
            stroke="currentColor"
            strokeWidth={strokeWidth}
            {...(family.dashes.length > 0 ? { strokeDasharray: family.dashes.join(' ') } : {})}
            {...(family.dashes.length > 0 && family.dashOffset !== 0
              ? { strokeDashoffset: family.dashOffset }
              : {})}
            {...(family.dotted ? { strokeLinecap: 'round' as const } : {})}
          />
        ))
      )}
    </svg>
  );
}
