"""initial schema — playbook §2 DDL, plus flags (§18) and otp_codes (§13)

Creates the whole Garh AI schema in one revision: 18 tables, every check constraint,
every ``firm_id`` index, the pgcrypto extension behind ``gen_random_uuid()``, and a
``BEFORE UPDATE`` trigger that maintains ``updated_at`` even for raw-SQL writers
(workers, the seed script, psql).

Hand-written rather than autogenerated so the constraint names, the partial indexes
and the identity column are exactly what ``garh_api/models.py`` declares —
``alembic revision --autogenerate`` against a database at this revision should produce
an empty diff.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-31

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())

#: Tables in creation order (drop order is the reverse).
TABLES: tuple[str, ...] = (
    "firms",
    "users",
    "projects",
    "plots",
    "briefs",
    "design_versions",
    "ops",
    "solver_jobs",
    "render_jobs",
    "sheets",
    "annotations",
    "compliance_reports",
    "share_links",
    "comments",
    "credit_events",
    "audit_log",
    "flags",
    "otp_codes",
)

_UPDATED_AT_FUNCTION = """
CREATE OR REPLACE FUNCTION garh_set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def _uuid_pk() -> sa.Column:
    return sa.Column(
        "id", UUID, server_default=sa.text("gen_random_uuid()"), nullable=False
    )


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def _firm_id(table: str) -> list[sa.schema.SchemaItem]:
    """``firm_id`` column + FK to firms, named the way models.py names it."""
    return [
        sa.Column("firm_id", UUID, nullable=False),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name="fk_%s_firm_id_firms" % table,
            ondelete="CASCADE",
        ),
    ]


def upgrade() -> None:
    # gen_random_uuid() lives in pgcrypto on Postgres 13/14; native from 13 onwards it
    # is also a core function, but the extension keeps this portable across managed
    # providers that pin older servers.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ------------------------------------------------------------------
    # firms
    # ------------------------------------------------------------------
    op.create_table(
        "firms",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("settings", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_firms"),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_firms_name_not_blank"),
    )
    op.create_index("ix_firms_created_at", "firms", ["created_at"])

    # ------------------------------------------------------------------
    # users
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        _uuid_pk(),
        *_firm_id("users"),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default=sa.text("'member'"), nullable=False),
        sa.Column("coa_number", sa.Text(), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("role IN ('admin', 'member')", name="ck_users_role"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.CheckConstraint("position('@' in email) > 1", name="ck_users_email_shape"),
    )
    op.create_index("ix_users_firm_id", "users", ["firm_id"])
    op.create_index("ix_users_firm_id_created_at", "users", ["firm_id", "created_at"])

    # ------------------------------------------------------------------
    # projects
    # ------------------------------------------------------------------
    op.create_table(
        "projects",
        _uuid_pk(),
        *_firm_id("projects"),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'draft'"), nullable=False),
        sa.Column("architect_of_record", UUID, nullable=True),
        sa.Column("units", sa.Text(), server_default=sa.text("'ft-in'"), nullable=False),
        sa.Column("city_pack", sa.Text(), nullable=True),
        sa.Column("demo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_projects"),
        sa.ForeignKeyConstraint(
            ["architect_of_record"],
            ["users.id"],
            name="fk_projects_architect_of_record_users",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'brief', 'options', 'design', 'drawings', 'archived')",
            name="ck_projects_status",
        ),
        sa.CheckConstraint("units IN ('ft-in', 'm')", name="ck_projects_units"),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_projects_name_not_blank"),
    )
    op.create_index("ix_projects_firm_id", "projects", ["firm_id"])
    op.create_index("ix_projects_firm_id_created_at", "projects", ["firm_id", "created_at"])
    op.create_index("ix_projects_firm_id_status", "projects", ["firm_id", "status"])

    # ------------------------------------------------------------------
    # plots (one per project)
    # ------------------------------------------------------------------
    op.create_table(
        "plots",
        _uuid_pk(),
        *_firm_id("plots"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("boundary", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("north_deg", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("roads", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column(
            "reg_profile", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("source", sa.Text(), server_default=sa.text("'manual'"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_plots"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_plots_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("project_id", name="uq_plots_project_id"),
        sa.CheckConstraint(
            "north_deg >= 0 AND north_deg < 360", name="ck_plots_north_deg_range"
        ),
        sa.CheckConstraint("source IN ('manual', 'dxf', 'seed')", name="ck_plots_source"),
        sa.CheckConstraint(
            "jsonb_typeof(boundary) = 'array'", name="ck_plots_boundary_array"
        ),
        sa.CheckConstraint("jsonb_typeof(roads) = 'array'", name="ck_plots_roads_array"),
    )
    op.create_index("ix_plots_firm_id", "plots", ["firm_id"])

    # ------------------------------------------------------------------
    # briefs (one per project)
    # ------------------------------------------------------------------
    op.create_table(
        "briefs",
        _uuid_pk(),
        *_firm_id("briefs"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("data", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("vastu_mode", sa.Text(), server_default=sa.text("'off'"), nullable=False),
        sa.Column("completeness", sa.Integer(), server_default=sa.text("0"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_briefs"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_briefs_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("project_id", name="uq_briefs_project_id"),
        sa.CheckConstraint(
            "vastu_mode IN ('off', 'advisory', 'strict')", name="ck_briefs_vastu_mode"
        ),
        sa.CheckConstraint(
            "completeness >= 0 AND completeness <= 100", name="ck_briefs_completeness_range"
        ),
    )
    op.create_index("ix_briefs_firm_id", "briefs", ["firm_id"])

    # ------------------------------------------------------------------
    # design_versions
    # ------------------------------------------------------------------
    op.create_table(
        "design_versions",
        _uuid_pk(),
        *_firm_id("design_versions"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("parent_id", UUID, nullable=True),
        sa.Column("version_branch", UUID, nullable=False),
        sa.Column("op_seq_start", sa.BigInteger(), nullable=True),
        sa.Column("op_seq_end", sa.BigInteger(), nullable=True),
        sa.Column("snapshot", JSONB, nullable=True),
        sa.Column("snapshot_hash", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), server_default=sa.text("'auto'"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_design_versions"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_design_versions_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["design_versions.id"],
            name="fk_design_versions_parent_id_design_versions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "kind IN ('auto', 'named', 'option')", name="ck_design_versions_kind"
        ),
        sa.CheckConstraint(
            "(snapshot IS NULL) = (snapshot_hash IS NULL)",
            name="ck_design_versions_snapshot_pair",
        ),
        sa.CheckConstraint(
            "kind <> 'named' OR name IS NOT NULL", name="ck_design_versions_named_has_name"
        ),
        sa.CheckConstraint(
            "op_seq_start IS NULL OR op_seq_end IS NULL OR op_seq_end >= op_seq_start",
            name="ck_design_versions_seq_order",
        ),
    )
    op.create_index("ix_design_versions_firm_id", "design_versions", ["firm_id"])
    op.create_index(
        "ix_design_versions_project_id_created_at",
        "design_versions",
        ["project_id", "created_at"],
    )
    op.create_index(
        "ix_design_versions_project_id_version_branch_op_seq_end",
        "design_versions",
        ["project_id", "version_branch", "op_seq_end"],
    )
    op.create_index("ix_design_versions_parent_id", "design_versions", ["parent_id"])

    # ------------------------------------------------------------------
    # ops — seq identity PK (§2 "bigserial"), unique(project, branch, idx)
    # ------------------------------------------------------------------
    op.create_table(
        "ops",
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
        *_firm_id("ops"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("version_branch", UUID, nullable=False),
        sa.Column("idx", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("payload", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("inverse", JSONB, nullable=True),
        sa.Column("actor", UUID, nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("client_op_id", sa.Text(), nullable=True),
        sa.Column("group_id", UUID, nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("seq", name="pk_ops"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_ops_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["actor"], ["users.id"], name="fk_ops_actor_users", ondelete="SET NULL"
        ),
        sa.UniqueConstraint(
            "project_id", "version_branch", "idx", name="uq_ops_project_id_version_branch_idx"
        ),
        sa.CheckConstraint("idx >= 0", name="ck_ops_idx_non_negative"),
        sa.CheckConstraint(
            "source IN ('manual', 'copilot', 'solver', 'system')", name="ck_ops_source"
        ),
        sa.CheckConstraint("length(btrim(type)) > 0", name="ck_ops_type_not_blank"),
        sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name="ck_ops_payload_object"),
    )
    op.create_index("ix_ops_firm_id", "ops", ["firm_id"])
    op.create_index(
        "ix_ops_project_id_version_branch_seq",
        "ops",
        ["project_id", "version_branch", "seq"],
    )
    # Partial unique: idempotent replay by clientOpId (§11), without forcing every op
    # to carry one.
    op.create_index(
        "uq_ops_project_id_client_op_id",
        "ops",
        ["project_id", "client_op_id"],
        unique=True,
        postgresql_where=sa.text("client_op_id IS NOT NULL"),
    )
    op.create_index(
        "ix_ops_project_id_group_id",
        "ops",
        ["project_id", "group_id"],
        postgresql_where=sa.text("group_id IS NOT NULL"),
    )

    # ------------------------------------------------------------------
    # solver_jobs
    # ------------------------------------------------------------------
    op.create_table(
        "solver_jobs",
        _uuid_pk(),
        *_firm_id("solver_jobs"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("params", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("options", JSONB, nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_solver_jobs"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_solver_jobs_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_solver_jobs_status",
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_solver_jobs_progress_range"
        ),
    )
    op.create_index("ix_solver_jobs_firm_id", "solver_jobs", ["firm_id"])
    op.create_index(
        "ix_solver_jobs_project_id_created_at", "solver_jobs", ["project_id", "created_at"]
    )
    op.create_index("ix_solver_jobs_firm_id_status", "solver_jobs", ["firm_id", "status"])

    # ------------------------------------------------------------------
    # render_jobs
    # ------------------------------------------------------------------
    op.create_table(
        "render_jobs",
        _uuid_pk(),
        *_firm_id("render_jobs"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("design_version_id", UUID, nullable=True),
        sa.Column("view", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("mode", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), server_default=sa.text("'mock'"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'queued'"), nullable=False),
        sa.Column("output_url", sa.Text(), nullable=True),
        sa.Column("params", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("stale", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_render_jobs"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_render_jobs_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["design_version_id"],
            ["design_versions.id"],
            name="fk_render_jobs_design_version_id_design_versions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_render_jobs_status",
        ),
        sa.CheckConstraint("mode IN ('precise', 'explore')", name="ck_render_jobs_mode"),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100", name="ck_render_jobs_progress_range"
        ),
    )
    op.create_index("ix_render_jobs_firm_id", "render_jobs", ["firm_id"])
    op.create_index(
        "ix_render_jobs_project_id_created_at", "render_jobs", ["project_id", "created_at"]
    )
    op.create_index("ix_render_jobs_firm_id_status", "render_jobs", ["firm_id", "status"])
    op.create_index(
        "ix_render_jobs_design_version_id", "render_jobs", ["design_version_id"]
    )

    # ------------------------------------------------------------------
    # sheets
    # ------------------------------------------------------------------
    op.create_table(
        "sheets",
        _uuid_pk(),
        *_firm_id("sheets"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("design_version_id", UUID, nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("number", sa.Text(), nullable=True),
        sa.Column("layout", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_sheets"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_sheets_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["design_version_id"],
            ["design_versions.id"],
            name="fk_sheets_design_version_id_design_versions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "kind IN ('site', 'floor', 'elevation', 'section', 'schedule', 'area-statement')",
            name="ck_sheets_kind",
        ),
    )
    op.create_index("ix_sheets_firm_id", "sheets", ["firm_id"])
    op.create_index(
        "ix_sheets_project_id_design_version_id",
        "sheets",
        ["project_id", "design_version_id"],
    )

    # ------------------------------------------------------------------
    # annotations
    # ------------------------------------------------------------------
    op.create_table(
        "annotations",
        _uuid_pk(),
        *_firm_id("annotations"),
        sa.Column("sheet_id", UUID, nullable=False),
        sa.Column("anchor_element_id", sa.Text(), nullable=True),
        sa.Column(
            "anchor_kind", sa.Text(), server_default=sa.text("'element'"), nullable=False
        ),
        sa.Column("payload", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("orphaned", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_annotations"),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["sheets.id"],
            name="fk_annotations_sheet_id_sheets",
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "anchor_kind IN ('element', 'dimension', 'point', 'sheet')",
            name="ck_annotations_anchor_kind",
        ),
        sa.CheckConstraint(
            "anchor_kind = 'sheet' OR anchor_element_id IS NOT NULL",
            name="ck_annotations_anchor_present",
        ),
    )
    op.create_index("ix_annotations_firm_id", "annotations", ["firm_id"])
    op.create_index("ix_annotations_sheet_id", "annotations", ["sheet_id"])
    op.create_index(
        "ix_annotations_sheet_id_orphaned", "annotations", ["sheet_id", "orphaned"]
    )

    # ------------------------------------------------------------------
    # compliance_reports
    # ------------------------------------------------------------------
    op.create_table(
        "compliance_reports",
        _uuid_pk(),
        *_firm_id("compliance_reports"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("design_version_id", UUID, nullable=True),
        sa.Column(
            "pack_versions", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("results", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_compliance_reports"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_compliance_reports_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["design_version_id"],
            ["design_versions.id"],
            name="fk_compliance_reports_design_version_id_design_versions",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(results) = 'array'", name="ck_compliance_reports_results_array"
        ),
    )
    op.create_index("ix_compliance_reports_firm_id", "compliance_reports", ["firm_id"])
    op.create_index(
        "ix_compliance_reports_project_id_created_at",
        "compliance_reports",
        ["project_id", "created_at"],
    )
    op.create_index(
        "ix_compliance_reports_design_version_id",
        "compliance_reports",
        ["design_version_id"],
    )

    # ------------------------------------------------------------------
    # share_links
    # ------------------------------------------------------------------
    op.create_table(
        "share_links",
        _uuid_pk(),
        *_firm_id("share_links"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("scope", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_by", UUID, nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_share_links"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_share_links_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_share_links_created_by_users",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint("token_hash", name="uq_share_links_token_hash"),
    )
    op.create_index("ix_share_links_firm_id", "share_links", ["firm_id"])
    op.create_index("ix_share_links_project_id", "share_links", ["project_id"])

    # ------------------------------------------------------------------
    # comments
    # ------------------------------------------------------------------
    op.create_table(
        "comments",
        _uuid_pk(),
        *_firm_id("comments"),
        sa.Column("project_id", UUID, nullable=False),
        sa.Column("share_link_id", UUID, nullable=True),
        sa.Column("anchor", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_name", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_comments"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_comments_project_id_projects",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["share_link_id"],
            ["share_links.id"],
            name="fk_comments_share_link_id_share_links",
            ondelete="SET NULL",
        ),
        sa.CheckConstraint("length(btrim(body)) > 0", name="ck_comments_body_not_blank"),
    )
    op.create_index("ix_comments_firm_id", "comments", ["firm_id"])
    op.create_index(
        "ix_comments_project_id_created_at", "comments", ["project_id", "created_at"]
    )
    op.create_index("ix_comments_share_link_id", "comments", ["share_link_id"])

    # ------------------------------------------------------------------
    # credit_events
    # ------------------------------------------------------------------
    op.create_table(
        "credit_events",
        _uuid_pk(),
        *_firm_id("credit_events"),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("qty", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("meta", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_credit_events"),
        sa.CheckConstraint(
            "kind IN ('render', 'solver', 'llm', 'export')", name="ck_credit_events_kind"
        ),
        sa.CheckConstraint("qty > 0", name="ck_credit_events_qty_positive"),
    )
    op.create_index("ix_credit_events_firm_id", "credit_events", ["firm_id"])
    op.create_index(
        "ix_credit_events_firm_id_created_at", "credit_events", ["firm_id", "created_at"]
    )
    op.create_index("ix_credit_events_firm_id_kind", "credit_events", ["firm_id", "kind"])

    # ------------------------------------------------------------------
    # audit_log — no foreign keys: entries outlive the firm/user they describe
    # ------------------------------------------------------------------
    op.create_table(
        "audit_log",
        _uuid_pk(),
        sa.Column("firm_id", UUID, nullable=False),
        sa.Column("user_id", UUID, nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=True),
        sa.Column("meta", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_audit_log"),
        sa.CheckConstraint(
            "length(btrim(action)) > 0", name="ck_audit_log_action_not_blank"
        ),
        sa.CheckConstraint(
            "length(btrim(entity)) > 0", name="ck_audit_log_entity_not_blank"
        ),
    )
    op.create_index("ix_audit_log_firm_id", "audit_log", ["firm_id"])
    op.create_index("ix_audit_log_firm_id_created_at", "audit_log", ["firm_id", "created_at"])
    op.create_index("ix_audit_log_entity_entity_id", "audit_log", ["entity", "entity_id"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])

    # ------------------------------------------------------------------
    # flags — global feature flags, read at boot (§18)
    # ------------------------------------------------------------------
    op.create_table(
        "flags",
        _uuid_pk(),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_flags"),
        sa.UniqueConstraint("key", name="uq_flags_key"),
        sa.CheckConstraint("key = lower(key)", name="ck_flags_key_lowercase"),
        sa.CheckConstraint("length(btrim(key)) > 0", name="ck_flags_key_not_blank"),
    )

    # ------------------------------------------------------------------
    # otp_codes — email OTP, 10 min expiry / 5 attempts (§13)
    # ------------------------------------------------------------------
    op.create_table(
        "otp_codes",
        _uuid_pk(),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_otp_codes"),
        sa.CheckConstraint(
            "attempts >= 0 AND attempts <= 5", name="ck_otp_codes_attempts_range"
        ),
        sa.CheckConstraint("email = lower(email)", name="ck_otp_codes_email_lowercase"),
    )
    op.create_index("ix_otp_codes_email_created_at", "otp_codes", ["email", "created_at"])
    op.create_index("ix_otp_codes_expires_at", "otp_codes", ["expires_at"])

    # ------------------------------------------------------------------
    # updated_at trigger on every table
    # ------------------------------------------------------------------
    op.execute(_UPDATED_AT_FUNCTION)
    for table in TABLES:
        op.execute(
            "CREATE TRIGGER trg_%s_updated_at BEFORE UPDATE ON %s "
            "FOR EACH ROW EXECUTE FUNCTION garh_set_updated_at()" % (table, table)
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute("DROP TRIGGER IF EXISTS trg_%s_updated_at ON %s" % (table, table))
    op.execute("DROP FUNCTION IF EXISTS garh_set_updated_at()")

    for table in reversed(TABLES):
        # Indexes and constraints go with the table; the FK graph is drop-safe in
        # reverse creation order.
        op.drop_table(table)

    # Safe here because this is the first revision: nothing else in this database can
    # depend on pgcrypto yet.
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
