#!/usr/bin/env python3
"""Guard: every absolute asset URL the web app hard-codes exists in ``public/``.

Why this exists
---------------
Phase 4 introduced ``LABEL_FONT_URL = '/fonts/inter-medium.woff'`` in
``apps/web/src/features/canvas/overlays/render/overlayMaterials.ts``. Every
troika ``Text`` on the drawing canvas — dimension values, room names, room
areas, compliance markers — is created with it.

A missing file there does not fail the build, does not fail a unit test, and
does not fail a typecheck. troika-three-text simply **falls back to fetching
Roboto from ``fonts.gstatic.com``**, which costs three things:

1. **A §13 CSP violation.** ``apps/web/nginx.conf`` ships
   ``font-src 'self' data'; connect-src 'self'``. In production the fetch is
   *blocked*, so the labels never render at all — a plan with no dimensions on
   it, and nothing in the console that names the cause.
2. **An offline failure.** ``docker compose up`` is meant to work with no
   internet (§1).
3. **A drawing that is not the drawing.** Dimension text metrics come from the
   font. A fallback face has different advance widths, so the label boxes
   ``overlays/tags/placement.ts`` packed no longer match the glyphs drawn in
   them and labels overlap at exactly the zoom levels the placer was tuned for.

That is a shipping blocker with no automated tripwire, so this is the tripwire.
It runs on a bare interpreter — no node, no pnpm — which is the point: it is
useful before the toolchain exists.

What counts as an asset reference
---------------------------------
A string literal in ``apps/web/src`` (or ``apps/web/index.html``) that starts
with ``/`` and ends in one of :data:`ASSET_SUFFIXES`. Those are served verbatim
from ``apps/web/public`` by Vite in dev and by nginx in production; anything
imported through the bundler (``import url from './x.png'``) is resolved by
Vite and is not this script's business.

Usage::

    python3 scripts/check_web_assets.py            # from the repo root
"""

from __future__ import annotations

import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB_SRC = os.path.join(REPO_ROOT, "apps", "web", "src")
WEB_PUBLIC = os.path.join(REPO_ROOT, "apps", "web", "public")
WEB_INDEX = os.path.join(REPO_ROOT, "apps", "web", "index.html")

ASSET_SUFFIXES = (
    ".woff2",
    ".woff",
    ".ttf",
    ".otf",
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".svg",
    ".ico",
    ".json",
    ".glb",
    ".gltf",
    ".hdr",
    ".exr",
)

# Paths that are produced at runtime or served by the API rather than shipped in
# public/. Each entry needs a reason — the allowlist is how this script stays
# honest instead of being turned off.
ALLOWED_MISSING = {
    # Vite rewrites these itself from index.html / the manifest.
    "/manifest.webmanifest": "generated by the build",
}

# THE BASELINE. Assets that are genuinely absent right now, each with the reason
# and the fix. They print a WARNING on every run and do NOT fail the gate, so
# that `make bare` keeps meaning "the dependency-free proofs pass" — but any
# asset that is not on this list and not on disk fails hard.
#
# An entry here is a debt, not a dispensation. Delete it the moment the file
# lands; a stale entry is itself reported as a failure below.
#: Empty since 2026-08-26: inter-medium.woff (the last entry) landed — fetched
#: from the rsms/inter v3.19 GitHub release (OFL-1.1; licence text ships in the
#: release archive). New gaps get an entry here, never a silent pass.
KNOWN_GAPS: dict[str, str] = {}

STRING_LITERAL = re.compile(r"""['"`](/[A-Za-z0-9_\-./@]+)['"`]""")
# `href="/x.svg"` and friends in plain HTML.
HTML_ATTR = re.compile(r"""(?:href|src)=['"](/[A-Za-z0-9_\-./@]+)['"]""")


def source_files() -> list[str]:
    out: list[str] = []
    for dirpath, dirnames, filenames in os.walk(WEB_SRC):
        dirnames[:] = [d for d in dirnames if d not in ("node_modules", "dist", "coverage")]
        for name in filenames:
            if name.endswith((".ts", ".tsx", ".css")):
                out.append(os.path.join(dirpath, name))
    if os.path.isfile(WEB_INDEX):
        out.append(WEB_INDEX)
    return sorted(out)


def references() -> dict[str, list[str]]:
    """asset path -> the files that name it."""
    found: dict[str, list[str]] = {}
    for path in source_files():
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        pattern = HTML_ATTR if path.endswith(".html") else STRING_LITERAL
        for match in pattern.finditer(text):
            url = match.group(1)
            if not url.lower().endswith(ASSET_SUFFIXES):
                continue
            rel = os.path.relpath(path, REPO_ROOT)
            found.setdefault(url, [])
            if rel not in found[url]:
                found[url].append(rel)
    return found


def main(argv: list[str]) -> int:
    del argv
    if not os.path.isdir(WEB_PUBLIC):
        print("FAIL  apps/web/public does not exist")
        return 1

    found = references()
    missing: list[tuple[str, list[str]]] = []
    gaps: list[tuple[str, list[str]]] = []
    for url, sources in sorted(found.items()):
        if url in ALLOWED_MISSING:
            continue
        on_disk = os.path.join(WEB_PUBLIC, url.lstrip("/"))
        if os.path.isfile(on_disk):
            continue
        (gaps if url in KNOWN_GAPS else missing).append((url, sources))

    # A baseline entry whose file has landed (or whose reference has gone) is
    # stale, and a stale baseline is how a gate quietly stops gating.
    stale = [
        url
        for url in KNOWN_GAPS
        if url not in found or os.path.isfile(os.path.join(WEB_PUBLIC, url.lstrip("/")))
    ]

    print(
        "web-assets: %d absolute asset URLs referenced, %d allowlisted, %d known gaps"
        % (len(found), len(ALLOWED_MISSING), len(KNOWN_GAPS))
    )

    for url, sources in gaps:
        print("WARN  %s is MISSING — %s" % (url, KNOWN_GAPS[url]))
        for source in sources:
            print("        named by %s" % source)

    ok = True
    if missing:
        ok = False
        print("FAIL  referenced but not present in apps/web/public:")
        for url, sources in missing:
            print("        %s" % url)
            for source in sources:
                print("          named by %s" % source)
        print(
            "      These are served verbatim. A 404 here is silent at build time:\n"
            "      troika falls back to fonts.gstatic.com (blocked by the nginx CSP),\n"
            "      an <img> shows a broken icon. Add the file, or add it to\n"
            "      KNOWN_GAPS in this script with a reason and a fix."
        )
    if stale:
        ok = False
        print("FAIL  stale KNOWN_GAPS entries (the file is there, or nothing names it):")
        for url in stale:
            print("        %s — delete it from KNOWN_GAPS" % url)

    if ok:
        print(
            "web-assets: ok — no unexpected missing assets (%d known gap%s outstanding)"
            % (len(gaps), "" if len(gaps) == 1 else "s")
        )
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
