"""garh_model — the model core, Python side. THE CONTRACT the API and workers
code against, and the LOCKSTEP MIRROR of ``packages/model`` (TypeScript).

Read the modules in this order the first time:

===========  ==================================================================
units        integer-mm boundary: parse anything an architect types, format out
ids          ``type_<ulid>`` element identity (+ deterministic derived ids)
geometry     integer-mm 2D primitives, with an explicit exactness contract
model        the HouseModel document (section 3) and the ProjectDoc ops fold to
ops          the 32-op taxonomy (section 4) + OP_CATALOG (copilot prompt source)
validate     the fold invariants, with machine-readable rejection codes
rooms        planar-subdivision room detection with id preservation
fold         fold/replay/groups/undo + canonical_json + state_hash
===========  ==================================================================

CROSS-LANGUAGE CONTRACT
-----------------------
The two implementations must agree, and the agreement is TESTED, not assumed:

* ``fixtures/model/golden-units.json``  — 67 parse pairs + 16 must-fail inputs.
  Both ``units.py`` and ``units.test.ts`` read this file; neither keeps literals.
* ``fixtures/model/golden-states.json`` — op logs with their expected
  ``state_hash``. Both sides fold the ops and assert the same 64 hex chars. If
  this file goes red, the canvas and the server disagree about what a design IS.
* ``packages/model/schema/*.schema.json`` — the shape both sides serialise.

EVERY LENGTH IS INTEGER MILLIMETRES. Areas are integer mm^2, angles integer
degrees. Display conversion (ft-in / m / gaj) happens only at the boundary, in
:mod:`garh_model.units`.
"""

from __future__ import annotations

from .fold import (
    CANONICAL_JSON_SPEC,
    STATE_HASH_ALGORITHM,
    CanonicalJsonError,
    FoldOutcome,
    FoldResult,
    GroupResult,
    UndoEntry,
    UndoStack,
    apply_group,
    apply_merge_patch,
    assert_schema_version,
    canonical_json,
    compare_code_points,
    doc_hash,
    fold,
    invert_merge_patch,
    locked_room_ids,
    replay,
    stair_footprint_polygon,
    state_hash,
    storey_built_up_area_mm2,
    storey_carpet_area_mm2,
    try_fold,
    wall_length_mm,
)
from .geometry import (
    Bbox,
    Orientation,
    Polygon,
    Pt,
    Seg,
    SegIntersection,
    bbox,
    canonical_ring,
    ensure_ccw,
    jaccard,
    polygon_area_mm2,
    polygon_centroid,
    polygon_is_closed_ring,
    polygon_key,
    pt,
    rect_polygon,
    segment_length_mm,
)
from .ids import (
    ELEMENT_TYPES,
    ID_PATTERN,
    IdError,
    ParsedId,
    derived_id,
    derived_id_unique,
    id_type,
    is_id,
    is_id_of,
    new_id,
    parse_id,
    seeded_ulid_factory,
    set_ulid_factory,
    try_parse_id,
)
from .model import (
    DEFAULTS,
    HABITABLE_ROOM_TYPES,
    OPENING_KINDS,
    ROOM_TYPES,
    SCHEMA_VERSION,
    WALL_KINDS,
    Annotation,
    Balcony,
    BriefDoc,
    Column,
    FacadeComponent,
    FacadeModel,
    FurnitureInstance,
    HouseModel,
    LevelData,
    Levels,
    MaterialAssignment,
    Model,
    ModelMeta,
    Opening,
    PlotDoc,
    ProjectDoc,
    RegProfile,
    Road,
    Room,
    SizeMm,
    Slab,
    Stair,
    StairLanding,
    Storey,
    SurfaceGroupRef,
    Wall,
    building_height_mm,
    built_up_area_mm2,
    empty_project_doc,
    room_display_name,
    to_jsonable,
)
from .ops import (
    OP_CATALOG,
    OP_TYPES,
    Op,
    OpGroup,
    OpSpec,
    copilot_op_specs,
    get_op_spec,
    is_op,
    is_op_type,
    op,
    render_op_catalog_for_prompt,
)
from .rooms import DEFAULT_JACCARD_THRESHOLD, detect_rooms, match_rooms, room_candidates
from .sha256 import sha256_utf8
from .units import (
    UnitParseError,
    format_area,
    format_length,
    format_rupees,
    load_golden_units,
    parse_area_mm2,
    parse_length_mm,
    round_half_away_from_zero,
    try_parse_length_mm,
)
from .validate import (
    MAX_WALL_THICKNESS_MM,
    MIN_ROOM_AREA_MM2,
    STAIR_RISE_TOLERANCE_MM,
    VALIDATION_CODES,
    WALL_END_MARGIN_MM,
    OpRejectedError,
    ValidationIssue,
    assert_valid_model,
    is_acceptable,
    issues_by_code,
    render_issues_for_llm,
    validate_model,
    validate_op_against_doc,
    validate_op_shape,
)

__all__ = [
    # units
    "UnitParseError",
    "parse_length_mm",
    "try_parse_length_mm",
    "parse_area_mm2",
    "format_length",
    "format_area",
    "format_rupees",
    "round_half_away_from_zero",
    "load_golden_units",
    # ids
    "ELEMENT_TYPES",
    "ID_PATTERN",
    "IdError",
    "ParsedId",
    "new_id",
    "derived_id",
    "derived_id_unique",
    "parse_id",
    "try_parse_id",
    "is_id",
    "is_id_of",
    "id_type",
    "set_ulid_factory",
    "seeded_ulid_factory",
    # geometry
    "Pt",
    "Seg",
    "Bbox",
    "Polygon",
    "Orientation",
    "SegIntersection",
    "pt",
    "bbox",
    "rect_polygon",
    "polygon_area_mm2",
    "polygon_centroid",
    "polygon_is_closed_ring",
    "polygon_key",
    "canonical_ring",
    "ensure_ccw",
    "jaccard",
    "segment_length_mm",
    # model
    "SCHEMA_VERSION",
    "DEFAULTS",
    "ROOM_TYPES",
    "WALL_KINDS",
    "OPENING_KINDS",
    "HABITABLE_ROOM_TYPES",
    "SizeMm",
    "LevelData",
    "Storey",
    "Wall",
    "Opening",
    "Room",
    "StairLanding",
    "Stair",
    "Slab",
    "Column",
    "FurnitureInstance",
    "Balcony",
    "FacadeComponent",
    "FacadeModel",
    "SurfaceGroupRef",
    "MaterialAssignment",
    "Levels",
    "ModelMeta",
    "HouseModel",
    "Road",
    "RegProfile",
    "PlotDoc",
    "BriefDoc",
    "Annotation",
    "ProjectDoc",
    "Model",
    "empty_project_doc",
    "building_height_mm",
    "built_up_area_mm2",
    "room_display_name",
    "to_jsonable",
    # ops
    "Op",
    "OpGroup",
    "OpSpec",
    "OP_CATALOG",
    "OP_TYPES",
    "op",
    "get_op_spec",
    "is_op",
    "is_op_type",
    "copilot_op_specs",
    "render_op_catalog_for_prompt",
    # validate
    "ValidationIssue",
    "VALIDATION_CODES",
    "OpRejectedError",
    "validate_op_shape",
    "validate_op_against_doc",
    "validate_model",
    "assert_valid_model",
    "is_acceptable",
    "issues_by_code",
    "render_issues_for_llm",
    "WALL_END_MARGIN_MM",
    "STAIR_RISE_TOLERANCE_MM",
    "MAX_WALL_THICKNESS_MM",
    "MIN_ROOM_AREA_MM2",
    # rooms
    "detect_rooms",
    "match_rooms",
    "room_candidates",
    "DEFAULT_JACCARD_THRESHOLD",
    # fold
    "fold",
    "try_fold",
    "apply_group",
    "replay",
    "FoldResult",
    "FoldOutcome",
    "GroupResult",
    "UndoEntry",
    "UndoStack",
    "canonical_json",
    "compare_code_points",
    "state_hash",
    "doc_hash",
    "CANONICAL_JSON_SPEC",
    "STATE_HASH_ALGORITHM",
    "CanonicalJsonError",
    "apply_merge_patch",
    "invert_merge_patch",
    "stair_footprint_polygon",
    "wall_length_mm",
    "storey_carpet_area_mm2",
    "storey_built_up_area_mm2",
    "locked_room_ids",
    "assert_schema_version",
    # sha256
    "sha256_utf8",
]
