"""§7 step 4 — label placement: greedy, deterministic, never overlapping.

    4. **Label placement:** greedy on a collision grid (dims, text, symbols all
       register); on collision try flip side → shift along chain → shrink text one step
       → leader line. Never overlap; leader as last resort.

The escalation order is the whole design, and it is ordered by how much a draughtsman
would mind:

1. **base** — text centred on its segment, above the dimension line (see
   :func:`preferred_side`: our DIMSTYLE says ``dimtad = 1``).
2. **flip** — same position, other side of the line. Free: nobody notices.
3. **shift** — slide along the chain. Mildly unusual, still normal drafting.
4. **shrink** — one ISO step smaller (2.5 → 1.8mm). Visible, so it comes after moving.
5. **leader** — pull the text clear and point at the segment. Honest, but it is clutter,
   so it is genuinely last: nothing else could be made to fit.

Steps 1-4 are tried in that order *at each text size*, so shrinking only happens after
moving has been exhausted, exactly as written.

**Determinism** (§16 compares goldens with tolerance 0) comes from three properties:
labels are placed in a fixed order (chain level, then chain id, then segment index — so
the overall dimension wins a contested slot over a room's inner dim); candidate
positions are generated by a fixed integer sequence; and the grid is a plain dict of
integer cells with insertion-ordered buckets. No floats, no set iteration, no hashing of
anything but ints and strings. Two runs on the same input produce the same layout, and
the same layout in the same order.

**What registers as an obstacle:** every dimension line (so no label sits on another
chain's line), every label already placed, and every symbol/room-label box the caller
passes in — that last one is how the plan projector tells the dimension engine where the
room name blocks and door tags are. Witness lines deliberately do *not* register: a
witness line is the boundary of the segment a label sits inside, and blocking on it would
turn every label into a leader.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

from services.drawings.autodim.chains import DimChainInfo
from services.drawings.autodim.config import DEFAULT_CONFIG, AutoDimConfig
from services.drawings.autodim.extract import HORIZONTAL
from services.drawings.autodim.primitives import Point
from services.drawings.dimensions import LabelBox

STRATEGY_BASE = "base"
STRATEGY_FLIP = "flip"
STRATEGY_SHIFT = "shift"
STRATEGY_SHRINK = "shrink"
STRATEGY_LEADER = "leader"

#: Reported in the order of escalation, which is also how the stats table reads.
STRATEGIES: tuple[str, ...] = (
    STRATEGY_BASE,
    STRATEGY_FLIP,
    STRATEGY_SHIFT,
    STRATEGY_SHRINK,
    STRATEGY_LEADER,
)


class PlacementError(RuntimeError):
    """No collision-free position existed, even for a leader.

    Raised rather than overlapping. §7 says "never overlap", and a sheet that quietly
    stacks two numbers on top of each other is worse than a job that fails loudly: the
    architect can read a failure, and cannot read two superimposed dimensions.
    """


class CollisionGrid:
    """A uniform integer grid of occupied boxes. Deterministic and O(1)-ish per query.

    Not a quadtree, on purpose: cells are one text height across, a sheet holds a few
    hundred labels, and a dict of small lists is both faster in practice and trivially
    reproducible run to run.
    """

    __slots__ = ("_cell_mm", "_cells", "_boxes")

    def __init__(self, cell_mm: int) -> None:
        if cell_mm <= 0:
            raise ValueError("collision grid cell must be positive, got %d" % cell_mm)
        self._cell_mm = cell_mm
        self._cells: dict[tuple[int, int], list[int]] = {}
        self._boxes: list[LabelBox] = []

    @property
    def cell_mm(self) -> int:
        return self._cell_mm

    def _span(self, box: LabelBox) -> tuple[int, int, int, int]:
        cell = self._cell_mm
        return (
            _floor_div(box.x_mm, cell),
            _floor_div(box.y_mm, cell),
            _floor_div(box.x_mm + box.width_mm, cell),
            _floor_div(box.y_mm + box.height_mm, cell),
        )

    def add(self, box: LabelBox) -> None:
        index = len(self._boxes)
        self._boxes.append(box)
        x0, y0, x1, y1 = self._span(box)
        for cx in range(x0, x1 + 1):
            for cy in range(y0, y1 + 1):
                self._cells.setdefault((cx, cy), []).append(index)

    def collides(self, box: LabelBox) -> bool:
        x0, y0, x1, y1 = self._span(box)
        seen: list[int] = []
        for cx in range(x0, x1 + 1):
            for cy in range(y0, y1 + 1):
                for index in self._cells.get((cx, cy), ()):
                    if index in seen:
                        continue
                    seen.append(index)
                    if box.overlaps(self._boxes[index]):
                        return True
        return False

    def boxes(self) -> tuple[LabelBox, ...]:
        return tuple(self._boxes)

    def __len__(self) -> int:
        return len(self._boxes)


def _floor_div(value: int, divisor: int) -> int:
    """Floor division that also behaves for negative coordinates (Python's // does)."""
    return value // divisor


def preferred_side(chain: DimChainInfo) -> int:
    """Which side of the dimension line the text sits on before any collision.

    Not "away from the building" — **above the dimension line**, because that is what our
    own DIMSTYLE says: ``services.drawings.dxf.setup_dimstyle`` writes ``dimtad = 1``
    (text above the dimension line) with ``dimtih = dimtoh = 0`` (text aligned *with* the
    line). A CAD viewer re-rendering these dimensions from the DIMSTYLE puts the text
    there, so the primitives have to agree or the DXF and the SVG of one sheet disagree
    with each other.

    For a horizontal chain "above" is +y. For a vertical chain the text is rotated to read
    bottom-to-top, so the same rule in the rotated frame is -x — the left of the line,
    which is also where a draughtsman expects it.
    """
    return +1 if chain.orientation == HORIZONTAL else -1


@dataclass(frozen=True)
class PlacedLabel:
    """One dimension label, positioned. Everything the renderer needs, and no more."""

    id: str
    chain_id: str
    segment_index: int
    text: str
    #: Padded bounding box used for collision. Never overlaps another label's box.
    box: LabelBox
    #: Centre of the glyph box — the ``Text`` primitive's position.
    anchor: Point
    height_mm: int
    rotation_deg: int
    strategy: str
    flipped: bool
    shift_mm: int
    shrink_step: int
    leader_from: Point | None = None
    leader_to: Point | None = None

    @property
    def has_leader(self) -> bool:
        return self.leader_from is not None

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "chainId": self.chain_id,
            "segmentIndex": self.segment_index,
            "text": self.text,
            "box": [self.box.x_mm, self.box.y_mm, self.box.width_mm, self.box.height_mm],
            "anchor": list(self.anchor),
            "heightMm": self.height_mm,
            "rotationDeg": self.rotation_deg,
            "strategy": self.strategy,
            "flipped": self.flipped,
            "shiftMm": self.shift_mm,
            "shrinkStep": self.shrink_step,
            "leaderFrom": None if self.leader_from is None else list(self.leader_from),
            "leaderTo": None if self.leader_to is None else list(self.leader_to),
        }


@dataclass(frozen=True)
class PlacementStats:
    """What the placement pass had to do. Printed by the smoke run; watched in CI.

    This is the launch gate's early-warning signal: F7-A's ">=90% of dims accepted
    unedited" fails first as a rise in ``leader`` and ``shrink`` counts, long before an
    architect gets round to telling us.

    ``flipped``/``shifted``/``shrunk``/``leaders`` are **flag** counts and overlap: one
    label can be flipped *and* shifted, and every leader label is drawn one size down, so
    it also counts as shrunk. ``by_strategy`` is the partition — each label appears in
    exactly one bucket, named for the most severe rung it needed.
    """

    labels: int = 0
    base: int = 0
    flipped: int = 0
    shifted: int = 0
    shrunk: int = 0
    leaders: int = 0
    #: Labels whose final strategy was each of :data:`STRATEGIES`.
    by_strategy: tuple[tuple[str, int], ...] = ()

    def to_json(self) -> dict[str, Any]:
        return {
            "labels": self.labels,
            "base": self.base,
            "flipped": self.flipped,
            "shifted": self.shifted,
            "shrunk": self.shrunk,
            "leaders": self.leaders,
            "byStrategy": dict(self.by_strategy),
        }


def summarise(labels: Sequence[PlacedLabel]) -> PlacementStats:
    counts = {name: 0 for name in STRATEGIES}
    for label in labels:
        counts[label.strategy] = counts.get(label.strategy, 0) + 1
    return PlacementStats(
        labels=len(labels),
        base=sum(1 for label in labels if label.strategy == STRATEGY_BASE),
        flipped=sum(1 for label in labels if label.flipped),
        shifted=sum(1 for label in labels if label.shift_mm != 0),
        shrunk=sum(1 for label in labels if label.shrink_step > 0),
        leaders=sum(1 for label in labels if label.has_leader),
        by_strategy=tuple((name, counts[name]) for name in STRATEGIES),
    )


def dim_line_box(chain: DimChainInfo, config: AutoDimConfig) -> LabelBox:
    """The dimension line as an obstacle, one tick tall.

    Registering the lines is what stops a room's inner dimension from being written
    across an outer chain's line — a collision no reviewer would forgive and no
    text-versus-text test would catch.
    """
    thickness = max(1, config.tick_size_mm())
    start, end = chain.absolute_start_mm(), chain.absolute_end_mm()
    if chain.orientation == HORIZONTAL:
        return LabelBox(
            x_mm=start,
            y_mm=chain.line_mm - thickness // 2,
            width_mm=end - start,
            height_mm=thickness,
            owner_id="%s#line" % chain.id,
        )
    return LabelBox(
        x_mm=chain.line_mm - thickness // 2,
        y_mm=start,
        width_mm=thickness,
        height_mm=end - start,
        owner_id="%s#line" % chain.id,
    )


def _candidate_box(
    chain: DimChainInfo,
    *,
    along_mm: int,
    side: int,
    distance_mm: int,
    text_width_mm: int,
    text_height_mm: int,
    pad_mm: int,
    owner_id: str,
) -> tuple[LabelBox, Point]:
    """Turn a (position along, side, distance from line) triple into a box + anchor.

    ``distance_mm`` is the clearance between the dimension line and the near edge of the
    glyph box; ``side`` is +1/-1 on the perpendicular axis. Vertical chains rotate the
    text 90 degrees, so the glyph box's extents swap.
    """
    if chain.orientation == HORIZONTAL:
        ink_w, ink_h = text_width_mm, text_height_mm
        ink_x0 = along_mm - ink_w // 2
        ink_y0 = chain.line_mm + distance_mm if side > 0 else chain.line_mm - distance_mm - ink_h
    else:
        ink_w, ink_h = text_height_mm, text_width_mm
        ink_y0 = along_mm - ink_h // 2
        ink_x0 = chain.line_mm + distance_mm if side > 0 else chain.line_mm - distance_mm - ink_w
    box = LabelBox(
        x_mm=ink_x0 - pad_mm,
        y_mm=ink_y0 - pad_mm,
        width_mm=ink_w + 2 * pad_mm,
        height_mm=ink_h + 2 * pad_mm,
        owner_id=owner_id,
    )
    anchor = (ink_x0 + ink_w // 2, ink_y0 + ink_h // 2)
    return box, anchor


def _shift_sequence(step_mm: int, max_steps: int) -> tuple[int, ...]:
    """``0, +d, -d, +2d, -2d, ...`` — symmetric, deterministic, zero first."""
    out = [0]
    for k in range(1, max_steps + 1):
        out.append(k * step_mm)
        out.append(-k * step_mm)
    return tuple(out)


def place_labels(
    chains: Sequence[DimChainInfo],
    *,
    config: AutoDimConfig = DEFAULT_CONFIG,
    obstacles: Sequence[LabelBox] = (),
    grid: CollisionGrid | None = None,
) -> tuple[tuple[PlacedLabel, ...], CollisionGrid]:
    """§7 step 4 for a whole sheet. Returns the labels and the grid they filled.

    Pure with respect to its inputs: ``chains`` and ``obstacles`` are not mutated, and a
    fresh grid is created unless the caller passes one (the sheet renderer passes one in
    when dimensions share a grid with other annotation passes).
    """
    working = grid if grid is not None else CollisionGrid(config.grid_cell_mm())

    for box in obstacles:
        working.add(box)
    for chain in chains:
        working.add(dim_line_box(chain, config))

    ordered = sorted(chains, key=lambda c: (c.level, c.id))
    gap = config.text_gap_mm()
    pad = max(1, gap // 2)

    placed: list[PlacedLabel] = []
    for chain in ordered:
        for index, segment in enumerate(chain.chain.segments):
            label = _place_one(
                chain,
                index,
                segment.label(),
                config=config,
                grid=working,
                gap_mm=gap,
                pad_mm=pad,
            )
            working.add(label.box)
            placed.append(label)

    return tuple(placed), working


def _place_one(
    chain: DimChainInfo,
    index: int,
    text: str,
    *,
    config: AutoDimConfig,
    grid: CollisionGrid,
    gap_mm: int,
    pad_mm: int,
) -> PlacedLabel:
    """Place one label, escalating exactly as §7 step 4 prescribes."""
    owner_id = "%s#%d" % (chain.id, index)
    start, end = chain.segment_bounds(index)
    midpoint = (start + end) // 2

    base_side = preferred_side(chain)
    for shrink_step in range(config.text_height_steps):
        height = config.text_height_mm(shrink_step)
        width = config.text_width_mm(text, shrink_step)
        shifts = _shift_sequence(max(1, height // 2), config.max_shift_steps)

        for shift in shifts:
            for flip in (False, True):
                side = base_side if not flip else -base_side
                box, anchor = _candidate_box(
                    chain,
                    along_mm=midpoint + shift,
                    side=side,
                    distance_mm=gap_mm,
                    text_width_mm=width,
                    text_height_mm=height,
                    pad_mm=pad_mm,
                    owner_id=owner_id,
                )
                if grid.collides(box):
                    continue
                if flip and shift == 0 and shrink_step == 0:
                    strategy = STRATEGY_FLIP
                elif shrink_step > 0:
                    strategy = STRATEGY_SHRINK
                elif shift != 0:
                    strategy = STRATEGY_SHIFT
                elif flip:
                    strategy = STRATEGY_FLIP
                else:
                    strategy = STRATEGY_BASE
                return PlacedLabel(
                    id=owner_id,
                    chain_id=chain.id,
                    segment_index=index,
                    text=text,
                    box=box,
                    anchor=anchor,
                    height_mm=height,
                    rotation_deg=0 if chain.orientation == HORIZONTAL else 90,
                    strategy=strategy,
                    flipped=flip,
                    shift_mm=shift,
                    shrink_step=shrink_step,
                )

    return _place_with_leader(
        chain,
        index,
        text,
        config=config,
        grid=grid,
        gap_mm=gap_mm,
        pad_mm=pad_mm,
        owner_id=owner_id,
        midpoint=midpoint,
    )


def _place_with_leader(
    chain: DimChainInfo,
    index: int,
    text: str,
    *,
    config: AutoDimConfig,
    grid: CollisionGrid,
    gap_mm: int,
    pad_mm: int,
    owner_id: str,
    midpoint: int,
) -> PlacedLabel:
    """Last resort: park the text clear of everything and point at the segment.

    Searches outward from the dimension line in text-height steps, trying three
    positions along the chain at each distance. The search always terminates because
    obstacles are finite and each step moves strictly further out; the cap exists so a
    pathological input fails rather than hangs.
    """
    height = config.text_height_mm(1)  # one step down: a leader label is a small label
    width = config.text_width_mm(text, 1)
    step = height + gap_mm
    alongs = (0, width + gap_mm, -(width + gap_mm))
    base_side = preferred_side(chain)

    for k in range(1, config.max_leader_steps + 1):
        distance = gap_mm + k * step
        for along in alongs:
            # Outward first: the crowding a leader is escaping is almost always the
            # building side of the chain, so park the text on the open side.
            for side in (chain.outward, -chain.outward):
                box, anchor = _candidate_box(
                    chain,
                    along_mm=midpoint + along,
                    side=side,
                    distance_mm=distance,
                    text_width_mm=width,
                    text_height_mm=height,
                    pad_mm=pad_mm,
                    owner_id=owner_id,
                )
                if grid.collides(box):
                    continue
                # The leader runs from the segment's midpoint on the dimension line to
                # the near edge of the text box, so it points *at* what it measures.
                step_in = (height // 2) * (1 if side > 0 else -1)
                if chain.orientation == HORIZONTAL:
                    tip = (midpoint, chain.line_mm)
                    landing = (anchor[0], anchor[1] - step_in)
                else:
                    tip = (chain.line_mm, midpoint)
                    landing = (anchor[0] - step_in, anchor[1])
                return PlacedLabel(
                    id=owner_id,
                    chain_id=chain.id,
                    segment_index=index,
                    text=text,
                    box=box,
                    anchor=anchor,
                    height_mm=height,
                    rotation_deg=0 if chain.orientation == HORIZONTAL else 90,
                    strategy=STRATEGY_LEADER,
                    flipped=side != base_side,
                    shift_mm=along,
                    shrink_step=1,
                    leader_from=tip,
                    leader_to=landing,
                )

    raise PlacementError(
        "no collision-free position for label %s after %d leader steps — the sheet is "
        "over-full; reduce the scale or split the view rather than overlapping text"
        % (owner_id, config.max_leader_steps)
    )


__all__ = [
    "STRATEGIES",
    "STRATEGY_BASE",
    "STRATEGY_FLIP",
    "STRATEGY_LEADER",
    "STRATEGY_SHIFT",
    "STRATEGY_SHRINK",
    "CollisionGrid",
    "PlacedLabel",
    "PlacementError",
    "PlacementStats",
    "dim_line_box",
    "place_labels",
    "preferred_side",
    "summarise",
]
