"""Share-link repository plus the public token resolver (§13).

Token handling rules, non-negotiable:

* The plaintext token is generated by the caller (``secrets.token_urlsafe(32)`` →
  256-bit) and returned to the user **once**, by the create call. It is never stored.
* Only ``sha256(token)`` is stored, so a database dump does not hand out live links.
* Lookup is by hash, over an indexed unique column — constant work, no scanning.

:class:`ShareTokenResolver` is non-tenant by necessity: the public viewer presents a
token and nothing else, so resolving it is how the ``firm_id`` is discovered in the
first place. It returns identity and scope only — never project content — and the
caller uses it to build a ``share_viewer`` :class:`~garh_api.tenancy.TenantCtx`, after
which the read-only router uses ordinary scoped repositories.
"""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from garh_api import models
from garh_api.logging import get_logger
from garh_api.repositories._guards import require_project_in_firm
from garh_api.repositories.domain import ResolvedShare, ShareLink
from garh_api.tenancy import Page, ProjectScopedRepository, RepositoryUsageError

_log = get_logger(__name__)

#: Sections a share link can expose. The viewer surface has no write dependencies.
SHARE_SECTIONS: tuple[str, ...] = ("plan", "three_d", "renders", "sheets", "compliance")


def hash_share_token(token: str) -> str:
    """``sha256`` hex of a share token. The only form ever persisted."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


class ShareLinkRepository(ProjectScopedRepository[models.ShareLink, ShareLink]):
    """Manage share links for the caller's projects."""

    row_type = models.ShareLink
    entity_name = "share_link"

    def to_domain(self, row: models.ShareLink) -> ShareLink:
        return ShareLink.from_row(row)

    # -- reads ---------------------------------------------------------
    async def list_active_for_project(self, project_id: uuid.UUID) -> list[ShareLink]:
        now = datetime.now(timezone.utc)
        stmt = (
            self._project_scoped_select(project_id)
            .where(models.ShareLink.revoked.is_(False))
            .where(
                (models.ShareLink.expires_at.is_(None)) | (models.ShareLink.expires_at > now)
            )
            .order_by(models.ShareLink.created_at.desc())
        )
        return [self.to_domain(row) for row in await self._all(stmt)]

    async def list_all_for_project(
        self, project_id: uuid.UUID, *, limit: int | None = None, cursor: str | None = None
    ) -> Page[ShareLink]:
        return await self.list_for_project(project_id, limit=limit, cursor=cursor)

    # -- writes --------------------------------------------------------
    async def create(
        self,
        project_id: uuid.UUID,
        *,
        token: str,
        sections: list[str] | None = None,
        can_comment: bool = True,
        expires_at: datetime | None = None,
        extra_scope: dict[str, Any] | None = None,
    ) -> ShareLink:
        """Store a new link. Pass the *plaintext* token; only its hash is persisted.

        Return the plaintext to the user from the route — this layer cannot give it
        back later, by design.
        """
        self.ctx.require_write("creating a share link")
        if not token or len(token) < 32:
            raise RepositoryUsageError(
                "Share tokens must be at least 32 characters (256-bit random)."
            )
        chosen = list(sections) if sections else list(SHARE_SECTIONS)
        unknown = [s for s in chosen if s not in SHARE_SECTIONS]
        if unknown:
            raise RepositoryUsageError(
                "Unknown share section(s): %s. Allowed: %s."
                % (", ".join(unknown), ", ".join(SHARE_SECTIONS))
            )
        await require_project_in_firm(self._session, self.firm_id, project_id)

        scope: dict[str, Any] = {
            "projectId": str(project_id),
            "sections": chosen,
            "canComment": bool(can_comment),
        }
        if extra_scope:
            scope.update(extra_scope)

        row = self._new_row(
            project_id=project_id,
            token_hash=hash_share_token(token),
            scope=scope,
            expires_at=expires_at,
            revoked=False,
            created_by=self.actor_id,
        )
        await self._insert(row)
        self._log.info(
            "share_link.created",
            entity_id=str(row.id),
            project_id=str(project_id),
            sections=chosen,
            can_comment=bool(can_comment),
            expires_at=expires_at.isoformat() if expires_at else None,
        )
        return self.to_domain(row)

    async def revoke(self, share_link_id: uuid.UUID) -> ShareLink:
        """Kill a link immediately. Kept (not deleted) so the audit trail holds."""
        self.ctx.require_write("revoking a share link")
        row = await self._require_row(share_link_id)
        row.revoked = True
        await self.flush()
        self._log.info("share_link.revoked", entity_id=str(share_link_id))
        return self.to_domain(row)

    async def update_scope(
        self,
        share_link_id: uuid.UUID,
        *,
        sections: list[str] | None = None,
        can_comment: bool | None = None,
        expires_at: datetime | None = None,
    ) -> ShareLink:
        self.ctx.require_write("editing a share link")
        row = await self._require_row(share_link_id)
        scope = dict(row.scope or {})
        if sections is not None:
            unknown = [s for s in sections if s not in SHARE_SECTIONS]
            if unknown:
                raise RepositoryUsageError(
                    "Unknown share section(s): %s." % ", ".join(unknown)
                )
            scope["sections"] = list(sections)
        if can_comment is not None:
            scope["canComment"] = bool(can_comment)
        row.scope = scope
        if expires_at is not None:
            row.expires_at = expires_at
        await self.flush()
        return self.to_domain(row)


class ShareTokenResolver:
    """Non-tenant resolver: share token → firm / project / scope.

    Constructor::

        ShareTokenResolver(session: AsyncSession)

    No ``TenantCtx`` (there cannot be one yet — that is the point) and no subclassing
    of :class:`~garh_api.tenancy.Repository`. It reads exactly one table, returns
    exactly :class:`~garh_api.repositories.domain.ResolvedShare`, and cannot reach
    project content.
    """

    entity_name = "share_link"

    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def resolve(self, token: str) -> ResolvedShare | None:
        """Validate a plaintext token. Returns None if unknown, revoked or expired.

        One indistinguishable answer for all three failure modes on purpose: a viewer
        should not learn whether a link ever existed.
        """
        if not token:
            return None
        token_hash = hash_share_token(token)
        stmt = (
            select(models.ShareLink)
            .where(models.ShareLink.token_hash == token_hash)
            .where(models.ShareLink.revoked.is_(False))
            .limit(1)
        )
        result = await self._session.execute(stmt)
        row = result.scalars().first()
        if row is None:
            _log.info("share_link.resolve_failed", reason="unknown_or_revoked")
            return None
        if row.expires_at is not None and row.expires_at <= datetime.now(timezone.utc):
            _log.info(
                "share_link.resolve_failed", reason="expired", share_link_id=str(row.id)
            )
            return None
        return ResolvedShare(
            share_link_id=row.id,
            firm_id=row.firm_id,
            project_id=row.project_id,
            scope=dict(row.scope or {}),
            expires_at=row.expires_at,
        )

    async def purge_expired(self, *, before: datetime | None = None) -> int:
        """Delete links that expired before ``before`` (default: now).

        Housekeeping for a worker holding
        :func:`~garh_api.tenancy.system_unscoped_session` — it spans firms by nature.
        """
        cutoff = before or datetime.now(timezone.utc)
        result = await self._session.execute(
            delete(models.ShareLink)
            .where(models.ShareLink.expires_at.is_not(None))
            .where(models.ShareLink.expires_at <= cutoff)
        )
        count = int(result.rowcount or 0)
        if count:
            _log.info("share_link.purged_expired", count=count)
        return count


__all__ = [
    "SHARE_SECTIONS",
    "ShareLinkRepository",
    "ShareTokenResolver",
    "hash_share_token",
]
